version: "3.4"
services:
  config: #docker-compose up config
    container_name: imagecode.config
    image: imagecode:latest #docker build -f Dockerfile -t imagecode . 
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    build:
      context: .
      target: config
  debug: #docker-compose up debug
    container_name: imagecode.debug
    image: imagecode:latest #docker build -f Dockerfile -t imagecode . 
    build:
      context: .
      target: debug
    volumes:
      - ./src:/app/src
      - ./doc:/app/doc      
    ports:
      - 5000:5000
      - 5678:5678
  prod: #docker-compose up prod
    container_name: imagecode.prod
    image: imagecode:latest #docker build -f Dockerfile -t imagecode . 
    build:
      context: .
      target: prod
    ports:
      - 5000:5000
      - 5678:5678
    #volumes:
    #- ./src/:/app/src


#docker-compose up python