version: "3.4"
services:
  config: 
    container_name: imagecode.config
    image: imagecode:latest
    build:
      context: .
      target: config
    ports:
      - 5000:5000
  debug: #docker build -f Dockerfile -t imagecode . 
    container_name: imagecode.debug
    image: imagecode:latest
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      target: debug
    ports:
      - 5000:5000
      - 5678:5678

    #volumes:
    #- ./src/:/app


#docker-compose up python